### ISSUE TITLE
In bootstrap install process, openshift-kube-api-server namespace ip incorrect

### ISSUE THREAD

**Issue by tomas-ortega** [cgruver/okd4-upi-lab-setup#3]
Hello!

When bootstrap process are running... Can't finish, because IP of control plane machines, don't response, only the bootstrap machine :(

![Captura](https://user-images.githubusercontent.com/14965364/79280386-8477a980-7eb0-11ea-875f-95d5c3fbd293.PNG)

I don't know if i have a mistake, could you please, help me a little? :(

**Comment by cgruver** [comment]
Hey,

   Give me a little more insight.  Is 192.168.20.201 one of your masters?

Try using curl from your bastion host to see if you can connect to port 6443 on the masters directly, then see if you can connect through your load balancer.

It would also help to see you ha proxy.cfg file that you are using, as well as the DNS zone file with your A and SRV records.

The tutorial as written is built around a 10.11.11.0/24 network.  If you are using a different configuration, then it's possible that you missed changing one of the files that I provide.

**Comment by tomas-ortega** [comment]
Thanks a lot for you response :)

Well, really the problem is when master machine try to start the etcd operator... Can't do it

Then... If no etcd ready... Kube api server can't start

I'm trying to run lab with VirtualBox 6 but no luck :(

**Comment by cgruver** [comment]
I haven't tried it with VirtualBox.  I don't know that anyone in the OKD group has tried it either.

The currently working hypervisor platforms are KVM (libvirt), OVirt, and VMWare.

**Comment by tomas-ortega** [comment]
Mmm, maybe... The problem is i'm using Virtualbox 6.X with possibility to use nested virtualization... But i'm not using KVM

I will to try re-install with with virtualbox, but first, install KVM inside machines, i don't know if this will work

In your installation... Are you using VMWare?

**Comment by cgruver** [comment]
I'm using KVM on bare metal.  Intel NUC servers.

If you are using nested virtualization, I would recommend sticking with KVM.

 The kickstart and firstboot scripts for a lab-host in this repo will setup libvirt for nested virtualization.  Provisioning/Infrastructure/firstboot/lab-host.fb

I'm not using nested virtualization to run the cluster, but the hosts are provisioned for nested virtualization so that I can test KubeVirt.

**Comment by tomas-ortega** [comment]
Mmm, not luck :(

See my oc, when i do `oc get nodes`

![image](https://user-images.githubusercontent.com/14965364/79979097-43c7f380-84a1-11ea-8ee2-9804cbe1085e.png)

And, when i do: `oc get co`
![image](https://user-images.githubusercontent.com/14965364/79979162-5e01d180-84a1-11ea-88d8-a98d0355db29.png)

I think, the problem is etcd cluster operator can't start... And when i see the "describe"... : `oc describe co etcd`

![image](https://user-images.githubusercontent.com/14965364/79979279-8d184300-84a1-11ea-80cc-b6c48326fa6f.png)

I think is a problem with the start of co etcd...

**Comment by cgruver** [comment]
@tomas-ortega 

Hey, since you are deploying on a different platform than what I'm using in this lab tutorial, move this issue to https://github.com/openshift/okd.  You'll get a lot more eyeballs on it.  The OKD working group will be able to assist you.  I'm active on that project too.

It will also help if you gather installation logs and attach those to the issue:

```
openshift-install --dir=okd4-install gather bootstrap --bootstrap 10.11.11.49 --master 10.11.11.60 --master 10.11.11.61 --master 10.11.11.62
```

Replace the `okd4-install` dir with your install dir.
Replace the IP addresses with the IPs of your bootstrap and master nodes.
